# Kili Engine 2
# Config file for the engine
# .ini parser version 1.0

[Window]
name = "KiliEngine" 
# Quotes are not mandatory

fullscreen = false
borderless = false
resizable = true
always_on_top = false

# Window size if windowed
width = 800 
height = 800

vsync = false

# Fps limit, 0 -> unlimited, only work with vsync false
fps_limit = 60

[EventSystem]
logging = false


[Console]