# Kili Engine 2
# Config file for the engine
# Ini parser version 1.0

[Window]
fullscreen = false
borderless = false
resizable = true
always_on_top = false

[Event]
logging = false #should log events

[Console]