# Kili Engine 2
# Config file for the engine
# .ini parser version 1.0

[Window]
name = "KiliEngine" 
# Quotes are not mandatory

fullscreen = false
borderless = false
resizable = true
always_on_top = false

# Window size if windowed
width = 800 
height = 800

vsync = false

[EventSystem]
logging = false

# They are a lot especially the mouse so i don't log them if you don't need
logging_keyboard_events = false
logging_mouse_events = false

[Console]
# Filters trough logging levels to hide some of them
logging_info = true    # Disabled in Build configuration
logging_debug = true   # Disabled in Build configuration
logging_loading = true
logging_warning = true
logging_error = true

[Time]
# Fps limit, 0 -> unlimited, only work with vsync false
# Use integer
fps_max = 60

max_delta_time = 1.0

logging = true
log_interval = 1.0